server:
  port: 8100
spring:
  application:
    name: adjustment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.52.128.159:3306/insuranceDB
    username: thw
    password: thw19971017thw
    tomcat:
      max-wait: 10000
      min-idle: 20
      max-idle: 100
      max-active: 300
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
